#!/usr/bin/env python3
"""Attribute every difference between the original and retrained models' learned
(non-zero-coefficient) fragment sets to a specific cause.

A fragment gets a non-zero coefficient iff it appears in a TRAINING compound and
does not cancel out in every training reaction it takes part in. So the two sets
can only differ for these reasons:

  NOTATION       the same fragment written differently -- the original
                 vocabulary was generated by a 2021-era RDKit, the retrain by a
                 current one, and the canonical SMILES writer changed. Removed
                 first by re-canonicalising both sides with one RDKit.
  COMPOUND LOST  47 of the 673 KEGG training compounds have no ModelSEED
                 equivalent, so their reactions were dropped and fragments that
                 occur only in them disappeared from the retrain.
  DEPICTION      the same molecule is drawn differently in the two databases --
                 KEGG stores neutral structures, ModelSEED stores the pH-7
                 charged form, plus tautomer/stereo/aromaticity differences. The
                 fragment exists on one side only because the structure differs.
  CANCELLATION   the fragment is present in a training compound on both sides
                 but happens to cancel in every reaction on one of them.

Outputs results/fragment_difference_causes.json.
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
from rdkit import Chem, RDLogger
from scipy.io import loadmat

RDLogger.logger().setLevel(RDLogger.CRITICAL)

DATA = Path("/scratch/ctaylor/dgpredictor_repo/data")
RES = Path(__file__).resolve().parents[1] / "results"
PAD = 44


def canon(s: str) -> str:
    m = Chem.MolFromSmiles(s, sanitize=False)
    if m is None:
        return s
    try:
        return Chem.MolToSmiles(m, canonical=True)
    except Exception:
        return s


def main() -> None:
    # ---------- learned sets --------------------------------------------------
    b1 = (DATA / "group_names_r1.txt").read_text().split("\n")
    b2 = (DATA / "group_names_r2_py3_modified_manual.txt").read_text().split("\n")
    coef = np.load(RES / "base_coef.npy")
    base = {canon(n) for i, n in enumerate(b1) if coef[i] != 0}
    base |= {canon(n) for i, n in enumerate(b2) if coef[len(b1) + PAD + i] != 0}

    rows = [l.split("\t") for l in
            (RES / "learned_fingerprints.tsv").read_text().strip().split("\n")[1:]]
    new = {canon(r[1]) for r in rows}

    # ---------- per-compound decompositions ----------------------------------
    kd = json.loads((DATA / "decompose_vector_ac.json").read_text())
    kd2 = json.loads((DATA / "decompose_vector_ac_r2_py3_indent_modified_manual.json").read_text())
    md = json.loads((DATA / "modelseed_decompose_r1.json").read_text())
    md2 = json.loads((DATA / "modelseed_decompose_r2.json").read_text())

    def kegg_frags(c):
        return {canon(g) for g in kd.get(c, {})} | {canon(g) for g in kd2.get(c, {})}

    def ms_frags(c):
        return {canon(g) for g in md.get(c, {})} | {canon(g) for g in md2.get(c, {})}

    # ---------- training compound sets ---------------------------------------
    k2m = json.loads((DATA / "kegg_to_modelseed_compound_map.json").read_text())
    cc = loadmat(DATA / "component_contribution_python.mat")
    cids = [str(x).strip() for x in cc["train_cids"].flatten()]
    lost = [c for c in cids if c not in k2m]          # 47 unmappable
    kept = [c for c in cids if c in k2m]

    # fragment -> which KEGG training compounds carry it
    kmap: dict[str, set[str]] = {}
    for c in cids:
        for f in kegg_frags(c):
            kmap.setdefault(f, set()).add(c)
    mmap: dict[str, set[str]] = {}
    for c in kept:
        for f in ms_frags(k2m[c]):
            mmap.setdefault(f, set()).add(c)

    # ---------- classify ------------------------------------------------------
    only_base = base - new
    only_new = new - base

    cause_b = {"compound lost": 0, "depiction differs": 0,
               "cancellation / other": 0, "unexplained": 0}
    ex_b: dict[str, list] = {k: [] for k in cause_b}
    for f in only_base:
        holders = kmap.get(f, set())
        if not holders:
            cause_b["unexplained"] += 1
            continue
        if holders <= set(lost):
            cause_b["compound lost"] += 1
            if len(ex_b["compound lost"]) < 4:
                ex_b["compound lost"].append((f, sorted(holders)[:2]))
        elif any(f not in ms_frags(k2m[c]) for c in holders if c in k2m):
            cause_b["depiction differs"] += 1
            if len(ex_b["depiction differs"]) < 4:
                ex_b["depiction differs"].append((f, sorted(h for h in holders if h in k2m)[:2]))
        else:
            cause_b["cancellation / other"] += 1

    cause_n = {"depiction differs": 0, "cancellation / other": 0, "unexplained": 0}
    ex_n: dict[str, list] = {k: [] for k in cause_n}
    for f in only_new:
        holders = mmap.get(f, set())
        if not holders:
            cause_n["unexplained"] += 1
            continue
        if any(f not in kegg_frags(c) for c in holders):
            cause_n["depiction differs"] += 1
            if len(ex_n["depiction differs"]) < 4:
                ex_n["depiction differs"].append((f, sorted(holders)[:2]))
        else:
            cause_n["cancellation / other"] += 1

    out = {
        "learned_fragments_after_recanonicalising": {
            "original": len(base), "retrain": len(new),
            "shared": len(base & new),
            "only_original": len(only_base), "only_retrain": len(only_new),
        },
        "training_compounds": {
            "kegg_in_original": len(cids),
            "unmappable_to_modelseed": len(lost),
            "carried_into_retrain": len(kept),
        },
        "why_only_in_original": cause_b,
        "why_only_in_retrain": cause_n,
        "examples_only_original": {k: v for k, v in ex_b.items() if v},
        "examples_only_retrain": {k: v for k, v in ex_n.items() if v},
    }
    (RES / "fragment_difference_causes.json").write_text(json.dumps(out, indent=2))
    print(json.dumps(out, indent=2))


if __name__ == "__main__":
    main()
